
### Cars
GET http://localhost:4000/cars

### Login
GET http://localhost:4000/login

### Car by ID
GET http://localhost:4000/cars/6709a7f9508af8e9dee4d161

### Update Car
PUT http://localhost:4000/cars/6701df0a9a7bd20fd97d51ff HTTP/1.1
Content-Type: application/json

{
    "brand": "honda",
    "name": "accord",
    "year": "2016",
    "bodyStyle": "sedan",
    "color": "brown"
}
### Create Contact
POST http://localhost:4000/cars HTTP/1.1
Content-Type: application/json

{
    "brand": "mazda",
    "name": "cx-5",
    "year": "2018",
    "bodyStyle": "suv",
    "color": "white"
}
### Delete Contact
DELETE http://localhost:4000/cars/6701ec308855f38ab1448ae4 HTTP/1.1





### Users
GET https://cse-341-project2-bgqa.onrender.com/cars

### Contact by ID from Render
GET https://cse-341-project2-bgqa.onrender.com/cars/6709a7d0508af8e9dee4d160

### Update user
PUT https://cse-341-project2-bgqa.onrender.com/cars/6709a7f9508af8e9dee4d161
Content-Type: application/application/json

{
    "brand": "honda",
    "name": "accord",
    "year": "2016",
    "bodyStyle": "sedan",
    "color": "brown"
}

### Create Contact
POST https://cse-341-project2-bgqa.onrender.com/cars HTTP/1.1
Content-Type: application/json

{
    "brand": "mazda",
    "name": "cx-5",
    "year": "2018",
    "bodyStyle": "suv",
    "color": "white"
}

### Delete Contact
DELETE https://cse-341-project2-bgqa.onrender.com/cars/66f8ba74c2461c3a75a676a9 HTTP/1.1
